services:
  - type: web
    name: farming-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
